Fix setState regression
I have noticed the following regression after upgrade to enzyme 3.4.4.

> TypeError: ReactWrapper::setState() expects a function as its second argument

I think that we are closer to how React behaves this way: https://github.com/facebook/react/blob/5031ebf6beddf88cac15f4d2c9e91f8dbb91d59d/packages/react-reconciler/src/ReactFiberReconciler.js#L144-L153.